#!/usr/bin/env bash

set -ex

ROOT=$PWD
tar -xzf ${SOURCE0} --strip-components=1
cd "${ROOT}/gui"
yarn --check-files
NODE_OPTIONS=--openssl-legacy-provider \
	OUTPUT_DIR=$ROOT/service/server/router/web \
	yarn build
rm -rf node_modules
cd "${ROOT}/service"
go mod vendor
