name: copr-ci

permissions:
  contents: write

on:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      package:
        description: Pacakge to build
        required: false
        type: string
      no-check:
        description: Dont check updates
        required: false
        type: boolean
      no-push:
        description: Dont push changes
        required: false
        type: boolean
      no-trigger:
        description: Dont trigger rebuild
        required: false
        type: boolean

jobs:
  update-packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Python environment
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: |
          pip install --upgrade -r requirements.txt

      - name: Run Python script
        env:
          COPR_USER_ID: ${{ secrets.COPR_USER_ID }}
          COPR_PROJECT_UUID: ${{ secrets.COPR_PROJECT_UUID }}
        run: |
          python ci/copr-ci.py \
            $([ '${{ inputs.no-check }}' = true ] && echo '--no-check' || echo) \
            $([ '${{ inputs.no-push }}' = true ] && echo '--no-push' || echo) \
            $([ '${{ inputs.no-trigger }}' = true ] && echo '--no-trigger' || echo) \
            ${{ inputs.package }}
