name: obs-ci

permissions:
  contents: write

on:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"

jobs:
  update-packages:
    strategy:
      matrix:
        package: [nix-mount, sarasa-gothic-fonts, symbols-nerd-fonts, wezterm]
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Update ${{ matrix.package }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_TOKEN: ${{ secrets.OBS_TOKEN }}
          OBS_PROJECT: home:loichyan
        run: |
          ./scripts/obs-ci.py \
            --update \
            --commit \
            --release \
            -p ${{ matrix.package }}
