name: update

permissions:
  contents: write

on:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      args:
        type: string
        required: false
        description: Arguments passed to ci.py

jobs:
  update-packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Restore Rust toolchain cache
        uses: actions/cache/restore@v3
        id: restore-rust-toolchain-cache
        with:
          path: ~/.rustup
          key: setup-rust-toolchain-${{ runner.os }}-

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        id: setup-rust-toolchain
        if: steps.restore-rust-toolchain-cache.outputs.cache-hit != 'true'

      - name: Save Rust toolchain cache
        uses: actions/cache@v3
        with:
          path: ~/.rustup
          key: |
            setup-rust-toolchain-${{ runner.os }}-${{ steps.setup-rust-toolchain.outputs.cachekey }}

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Just
        uses: extractions/setup-just@v1

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt

      - name: Update packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_TOKEN: ${{ secrets.OBS_TOKEN }}
          OBS_PROJECT: home:loichyan
        run: |
          if [[ "${{ github.event_name }}" = "workflow_dispatch" ]]; \
          then ./ci.py ${{ inputs.args }}; \
          else ./ci.py --ci --all; \
          fi
