name: update

permissions:
  contents: write

on:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      args:
        type: string
        required: false
        description: Arguments passed to obs-ci.py

jobs:
  update-packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Cache Rust toolchain
        uses: actions/cache@v3
        id: cache-rust-toolchain
        with:
          path: ~/.rustup
          key: rust-toolchain

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        if: steps.cache-rust-toolchain.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          profile: minimal

      - name: Update packages
        if: github.event_name != 'schedule'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_TOKEN: ${{ secrets.OBS_TOKEN }}
          OBS_PROJECT: home:loichyan
        run: |
          [[ "${{ github.event_name }}" = "workflow_dispatch" ]] \
          && ./scripts/obs-ci.py ${{ inputs.args }} \
          || ./scripts/obs-ci.py --ci
